version: '3.8'
services:
  backend:
    build: ./backend
    container_name: projectrobotjl-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - projectrobotjl-net
  middleware:
    build: ./middleware
    container_name: projectrobotjl-middleware
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - projectrobotjl-net
    depends_on:
      - backend
  frontend:
    build: ./frontend
    container_name: projectrobotjl-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - projectrobotjl-net
networks:
  projectrobotjl-net:
    driver: bridge
